INFLUENCER_COLLABORATION: 
  terms:
    - "W ramach niniejszej Umowy Influencer zobowiązuje się do stworzenia i opublikowania 5 rolek i 5 postów"
    - "Wszystkie materiały muszą zawierać oznaczenia zamawiającego"
  conditions:
    - "Influencer zobowiązuje się do jednoznacznego, czytelnego i widocznego oznaczenia każdego Materiału jako treści reklamowej"
    - "Z chwilą ustalenia i zaakceptowania Materiałów (utworów), Influencer przenosi na Zamawiającego, bez dodatkowego wynagrodzenia, całościowe autorskie prawa majątkowe oraz prawa zależne do Materiałów na terytorium całego świata, na czas nieoznaczony"
LICENSING: